eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: "http://172.17.6.9:8080/service-registry/eureka"
  instance:
    hostname: "172.17.6.9"
common:
  name: "Spring"
